#!/bin/bash

# this does everything that is needed before "build"

# clean coreboot
cd coreboot
make clean

# rebuild cbfstool
cd util/cbfstool
make clean
make

# go back to coreboot dir
cd ../../

# remove the payloads (they will be built by "build")
rm -rf grub.elf
rm -rf grub_serial.elf

# build reference crossGCC for coreboot
make crossgcc-clean
make crossgcc

# rebuild grub
cd ..
cd grub
make clean
./autogen.sh
./configure --with-platform=coreboot
make

# rebuild memtest86+
cd ..
cd "memtest86+-5.01"
make clean
make

# rebuild bucts
cd ..
cd bucts
make clean
make

# rebuild flashrom
cd flashrom
make clean
make

# now make any changes needed elsewhere, and run "build".

